# Generated by Django 5.2.9 on 2026-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0003_fcmdevicetoken_queueentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='cohort',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EXAMINATION_CREATED', 'Examination Created'), ('EXAMINATION_UPDATED', 'Examination Updated'), ('EXAMINATION_FINALIZED', 'Examination Finalized'), ('APPOINTMENT_CREATED', 'Appointment Created'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_COMPLETED', 'Appointment Completed'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_CLOSED', 'Ticket Closed'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('PATIENT_QR_SCANNED', 'Patient QR Code Scanned'), ('PATIENT_HISTORY_VIEWED', 'Patient History Viewed'), ('PATIENT_RECORD_ACCESSED', 'Patient Record Accessed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_CHANGE_PASSWORD', 'User Change Password')], max_length=50),
        ),
    ]
