# Generated by Django 6.0.3 on 2026-04-29 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0005_user_address_user_date_of_birth_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EXAMINATION_CREATED', 'Examination Created'), ('EXAMINATION_UPDATED', 'Examination Updated'), ('EXAMINATION_FINALIZED', 'Examination Finalized'), ('APPOINTMENT_CREATED', 'Appointment Created'), ('APPOINTMENT_UPDATED', 'Appointment Updated'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_COMPLETED', 'Appointment Completed'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_CLOSED', 'Ticket Closed'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('PATIENT_QR_SCANNED', 'Patient QR Code Scanned'), ('PATIENT_HISTORY_VIEWED', 'Patient History Viewed'), ('PATIENT_RECORD_ACCESSED', 'Patient Record Accessed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_CHANGE_PASSWORD', 'User Change Password')], max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'ADMIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='examinations_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list, help_text='List of allergies'),
        ),
    ]
