# Generated by Django 6.0.3 on 2026-04-29 16:37

import ast
import json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_patientprofile_allergies(apps, schema_editor):
    PatientProfile = apps.get_model('mainAPI', 'PatientProfile')

    for profile in PatientProfile.objects.all().only('id', 'allergies'):
        raw_value = profile.allergies
        normalized = []

        if raw_value is None:
            normalized = []
        elif isinstance(raw_value, list):
            normalized = [str(item).strip() for item in raw_value if str(item).strip()]
        elif isinstance(raw_value, str):
            value = raw_value.strip()
            if not value:
                normalized = []
            else:
                parsed = None
                try:
                    parsed = json.loads(value)
                except Exception:
                    if value.startswith('[') and value.endswith(']'):
                        try:
                            parsed = ast.literal_eval(value)
                        except Exception:
                            parsed = None
                    if parsed is None:
                        parsed = [item.strip() for item in value.split(',') if item.strip()]

                if isinstance(parsed, list):
                    normalized = [str(item).strip() for item in parsed if str(item).strip()]
                else:
                    normalized = [str(parsed).strip()] if str(parsed).strip() else []
        else:
            normalized = [str(raw_value).strip()] if str(raw_value).strip() else []

        profile.allergies = json.dumps(normalized)
        profile.save(update_fields=['allergies'])


def drop_patientprofile_date_of_birth_if_exists(apps, schema_editor):
    PatientProfile = apps.get_model('mainAPI', 'PatientProfile')
    table_name = PatientProfile._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = [col.name for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)]

    if 'date_of_birth' in columns:
        field = PatientProfile._meta.get_field('date_of_birth')
        schema_editor.remove_field(PatientProfile, field)


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0005_user_address_user_date_of_birth_user_sex'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_patientprofile_date_of_birth_if_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='patientprofile',
                    name='date_of_birth',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EXAMINATION_CREATED', 'Examination Created'), ('EXAMINATION_UPDATED', 'Examination Updated'), ('EXAMINATION_FINALIZED', 'Examination Finalized'), ('APPOINTMENT_CREATED', 'Appointment Created'), ('APPOINTMENT_UPDATED', 'Appointment Updated'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_COMPLETED', 'Appointment Completed'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_CLOSED', 'Ticket Closed'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('PATIENT_QR_SCANNED', 'Patient QR Code Scanned'), ('PATIENT_HISTORY_VIEWED', 'Patient History Viewed'), ('PATIENT_RECORD_ACCESSED', 'Patient Record Accessed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_CHANGE_PASSWORD', 'User Change Password')], max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'ADMIN']}, on_delete=django.db.models.deletion.PROTECT, related_name='examinations_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(normalize_patientprofile_allergies, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list, help_text='List of allergies'),
        ),
    ]
