# Generated by Django 6.0.3 on 2026-05-30 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0006_remove_patientprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='prescription',
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('morning', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('before_meal', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='mainAPI.examination')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
