# Generated by Django 6.0.3 on 2026-05-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0008_add_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
